#!/bin/bash
# file: DBMcalc

subj=$1
WORKDIR=$2
OUTDIR=$3

SUBJECTS_DIR=${WORKDIR}/${OUTDIR}/FS
mkdir -p ${SUBJECTS_DIR}

mkdir -p ${WORKDIR}/${OUTDIR}/subjs/${subj}

#set ANTs resources

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$ncpus
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS

DenoiseImage -d 3 -i T1.nii -o ${WORKDIR}/${OUTDIR}/subjs/${subj}/T1_dn.nii.gz

cd ${WORKDIR}/${OUTDIR}/subjs/${subj}

recon-all -autorecon1 -autorecon2 -i T1_dn.nii.gz -subjid $subj -sd $SUBJECTS_DIR -no-isrunning -mprage

mri_vol2vol --mov $SUBJECTS_DIR/$subj/mri/brain.mgz --targ $SUBJECTS_DIR/$subj/mri/rawavg.mgz --regheader --o brainFSnat.nii

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [brainFS_in2009, brainFS_in2009Warped.nii.gz, brainFS_in2009InverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 1 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [/mnt/backedup/home/alistaiP/base/2009c_brain.nii, brainFSnat.nii,1] --transform Rigid[0.1] --metric MI[/mnt/backedup/home/alistaiP/base/2009c_brain.nii, brainFSnat.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[/mnt/backedup/home/alistaiP/base/2009c_brain.nii, brainFSnat.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[/mnt/backedup/home/alistaiP/base/2009c_brain.nii, brainFSnat.nii,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

CreateJacobianDeterminantImage 3 brainFS_in20091Warp.nii.gz brainFS_absJAc.nii.gz 1


#smoothing

fslmaths brainFS_absJAc.nii.gz -s 2 brainFS_absJAc_2mm_fwhm.nii.gz

fslmaths brainFS_absJAc.nii.gz -s 8 brainFS_absJAc_8mm_fwhm.nii.gz


#Disease calculation 

rm *mm.txt

mrstats -output mean brainFS_absJAc_2mm_fwhm.nii.gz -mask /mnt/backedup/home/alistaiP/bundle/test/PDdiffusion/misc/melodic_IC_0007_thr3_1mm.nii.gz > ${subj}_DBM_dis_mean_2mm.txt

mrstats -output mean brainFS_absJAc_8mm_fwhm.nii.gz -mask /mnt/backedup/home/alistaiP/bundle/test/PDdiffusion/misc/melodic_IC_0007_thr3_1mm.nii.gz > ${subj}_DBM_dis_mean_8mm.txt


mrstats -output median brainFS_absJAc_2mm_fwhm.nii.gz -mask /mnt/backedup/home/alistaiP/bundle/test/PDdiffusion/misc/melodic_IC_0007_thr3_1mm.nii.gz >  ${subj}_DBM_dis_med_2mm.txt

mrstats -output median brainFS_absJAc_8mm_fwhm.nii.gz -mask /mnt/backedup/home/alistaiP/bundle/test/PDdiffusion/misc/melodic_IC_0007_thr3_1mm.nii.gz >  ${subj}_DBM_dis_med_8mm.txt
